// programmesImportData.ts
// Create this file to hold the transformed data from your admission documents

import { ProgrammeData } from '@/constants/programmesData';

// Transform the admission document data into the ProgrammeData format
export const MZUZU_PROGRAMMES_FROM_PROSPECTUS: ProgrammeData[] = [
  // FACULTY OF EDUCATION - Upgrading Programmes (Face-to-Face)
  {
    name: "Bachelor of Education (Arts) - Upgrading (2 Years)",
    description: "Upgrading programme for Diploma in Education holders to Bachelor's degree in Arts Education. Graduates qualify to teach secondary subjects including History, Geography, and Bible Knowledge.",
    department: "Faculty of Education",
    duration: "2 Years",
    category: "upgrading",
    code: "BED-ARTS-UPG-2YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Education",
    entry_requirements: "• Diploma in Education or equivalent from accredited institution\n• MSCE with at least 4 credits including English + any 3 of: History, Geography, Social and Development Studies, Bible Knowledge, Chichewa, French\n• Qualified to teach any 2 secondary subjects: History, Geography, Bible Knowledge, Chichewa, French"
  },
  {
    name: "Bachelor of Education (Arts) - Upgrading (4 Years)",
    description: "Upgrading programme for T2 Teaching Certificate holders to Bachelor's degree in Arts Education.",
    department: "Faculty of Education",
    duration: "4 Years",
    category: "upgrading",
    code: "BED-ARTS-UPG-4YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Education",
    entry_requirements: "• MSCE aggregate ≤30 points with at least 6 credits including English + any 3 of: History, Geography, Social and Development Studies, Bible Knowledge, Chichewa, French\n• T2 Teaching Certificate\n• Ready to teach any 2 of: History, Geography, Bible Knowledge"
  },
  {
    name: "Bachelor of Education (Languages) - Upgrading (2 Years)",
    description: "Upgrading programme focusing on language education including English, Chichewa, and French.",
    department: "Faculty of Education",
    duration: "2 Years",
    category: "upgrading",
    code: "BED-LANG-UPG-2YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Education",
    entry_requirements: "• Diploma in Education or equivalent\n• MSCE with at least 4 credits including English + Chichewa or French + any 2 of: History, Geography, Social and Development Studies, Bible Knowledge\n• Qualified to teach any 2 of: English, Chichewa, French"
  },
  {
    name: "Bachelor of Education (Languages) - Upgrading (4 Years)",
    description: "Upgrading programme for T2 certificate holders to Bachelor's degree in Languages Education.",
    department: "Faculty of Education",
    duration: "4 Years",
    category: "upgrading",
    code: "BED-LANG-UPG-4YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Education",
    entry_requirements: "• MSCE aggregate ≤30 points with at least 6 credits including English + Chichewa or French + any 2 of: History, Geography, Biology, Bible Knowledge\n• T2 Teaching Certificate\n• Ready to teach any 2 of: English, Chichewa, French"
  },
  {
    name: "Bachelor of Education (Science) - Upgrading (2 Years)",
    description: "Upgrading programme for Diploma in Science Education holders to Bachelor's degree.",
    department: "Faculty of Education",
    duration: "2 Years",
    category: "upgrading",
    code: "BED-SCI-UPG-2YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Education",
    entry_requirements: "• Diploma in Education (Sciences) or equivalent\n• MSCE with at least 4 credits including English, Mathematics/Additional Mathematics, Biology, Physical Science or Physics & Chemistry\n• Qualified to teach any 2 of: Mathematics, Physics, Chemistry, Biology"
  },
  {
    name: "Bachelor of Education (Science) - Upgrading (4 Years)",
    description: "Upgrading programme for T2 certificate holders to Bachelor's degree in Science Education.",
    department: "Faculty of Education",
    duration: "4 Years",
    category: "upgrading",
    code: "BED-SCI-UPG-4YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Education",
    entry_requirements: "• MSCE aggregate ≤30 points with at least 6 credits including English, Mathematics/Add. Mathematics, Biology, Physical Science or Physics & Chemistry\n• T2 Teaching Certificate\n• Ready to teach any 2 of: Mathematics, Biology, Chemistry, Physics"
  },
  {
    name: "Bachelor of Education (ICT) - Upgrading",
    description: "Upgrading programme for T2 certificate holders to Bachelor's degree in ICT Education, focusing on Computer Studies and Mathematics.",
    department: "Faculty of Education",
    duration: "4 Years",
    category: "upgrading",
    code: "BED-ICT-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Education",
    entry_requirements: "• MSCE with at least 6 credits including English, Mathematics, Computer Studies + any 3 of: Physics, Chemistry, Biology, Geography, Technical Drawing, Woodwork\n• T2 Teaching Certificate\n• Ready to teach Computer Studies and Mathematics"
  },

  // FACULTY OF HUMANITIES AND SOCIAL SCIENCES - Upgrading
  {
    name: "Bachelor of Arts (Theology & Religious Studies) - Upgrading",
    description: "Upgrading programme for Diploma holders in Theology and Religious Studies.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "2 Years",
    category: "upgrading",
    code: "BA-TRS-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "• Diploma in Theology & Religious Studies or equivalent\n• MSCE with at least 4 credits including English + Bible Knowledge or History + any 1 of: Social and Development Studies, Geography, Chichewa, French"
  },
  {
    name: "Bachelor of Arts (Security Studies) - Upgrading (4 Years)",
    description: "Upgrading programme for security personnel with MSCE and work experience.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "upgrading",
    code: "BA-SEC-UPG-4YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "• MSCE aggregate ≤30 points with at least 6 credits including English & Mathematics\n• At least 2 years' work experience in defence/security service\n• Evidence of current employment in defence/security sector"
  },
  {
    name: "Bachelor of Arts (Security Studies) - Upgrading (2 Years)",
    description: "Upgrading programme for Diploma holders in Peace and Security Studies.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "2 Years",
    category: "upgrading",
    code: "BA-SEC-UPG-2YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "• Diploma in Peace & Security Studies or equivalent\n• MSCE with at least 4 credits including English\n• At least 2 years' current work experience in defence/security\n• Evidence of current employment in defence/security sector"
  },

  // FACULTY OF ENVIRONMENTAL SCIENCES - Upgrading
  {
    name: "Bachelor of Science (Forestry) - Upgrading (3 Years)",
    description: "Upgrading programme for Certificate holders in Forestry or related fields.",
    department: "Faculty of Environmental Sciences",
    duration: "3 Years",
    category: "upgrading",
    code: "BSC-FOR-UPG-3YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Certificate in Forestry, Agriculture or related field\n• MSCE aggregate ≤30 points with at least 6 credits including English, Biology, Mathematics, Physics/Chemistry/Physical Science + any other science-related subjects"
  },
  {
    name: "Bachelor of Science (Forestry) - Upgrading (2 Years)",
    description: "Upgrading programme for Diploma holders in Forestry or related fields.",
    department: "Faculty of Environmental Sciences",
    duration: "2 Years",
    category: "upgrading",
    code: "BSC-FOR-UPG-2YR",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Diploma in Forestry, Agriculture or related field\n• MSCE with at least 4 credits including English, Biology, Mathematics + any other science-related subjects"
  },
  {
    name: "Bachelor of Science (Fisheries & Aquatic Sciences) - Upgrading",
    description: "Upgrading programme for Certificate holders in Fisheries, Agriculture, or Animal Science.",
    department: "Faculty of Environmental Sciences",
    duration: "4 Years",
    category: "upgrading",
    code: "BSC-FAS-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Certificate in Fisheries/Agriculture/Animal Science or related\n• MSCE aggregate ≤30 points with at least 6 credits including English, Biology, Physical Science, Mathematics + any other science-related subjects"
  },
  {
    name: "Bachelor of Science (Land Surveying) - Upgrading",
    description: "Upgrading programme for Diploma holders in Land Surveying.",
    department: "Faculty of Environmental Sciences",
    duration: "3-4 Years",
    category: "upgrading",
    code: "BSC-LSURV-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Diploma in Land Surveying or related field\n• MSCE with at least 4 credits including Mathematics, English, Geography"
  },
  {
    name: "Bachelor of Science (Estate Management) - Upgrading",
    description: "Upgrading programme for Diploma holders in Estate Management.",
    department: "Faculty of Environmental Sciences",
    duration: "3-4 Years",
    category: "upgrading",
    code: "BSC-ESTATE-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Diploma in Estate Management or related field\n• MSCE with at least 4 credits including English, Mathematics, Geography"
  },
  {
    name: "Bachelor of Science (Town & Regional Planning) - Upgrading",
    description: "Upgrading programme for Diploma holders in Town Planning.",
    department: "Faculty of Environmental Sciences",
    duration: "3-4 Years",
    category: "upgrading",
    code: "BSC-TRP-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Diploma in Town Planning or related field\n• MSCE with at least 4 credits including English, Mathematics, Geography"
  },
  {
    name: "Bachelor of Science (Water Resources Engineering & Management) - Upgrading",
    description: "Upgrading programme for Diploma holders in Hydrology, Engineering, or Agriculture.",
    department: "Faculty of Environmental Sciences",
    duration: "3-4 Years",
    category: "upgrading",
    code: "BSC-WREM-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Diploma in Hydrology, Civil/Mechanical Engineering, Agriculture, Irrigation Technology\n• MSCE with at least 4 credits including Mathematics, Physical Science/Physics/Chemistry/Biology, English, Geography"
  },
  {
    name: "Bachelor of Science (Transformative Community Development) - Upgrading",
    description: "Upgrading programme for Diploma holders in Community Development or related fields.",
    department: "Faculty of Environmental Sciences",
    duration: "3-4 Years",
    category: "upgrading",
    code: "BSC-TCD-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Diploma in Community Development, Agriculture Education, Rural Development, Agricultural Extension\n• MSCE with at least 4 credits including English, Agriculture, Biology, Mathematics"
  },
  {
    name: "Bachelor of Science (Value Chain Agriculture) - Upgrading",
    description: "Upgrading programme for Diploma holders in Agriculture, Agribusiness, or related fields.",
    department: "Faculty of Environmental Sciences",
    duration: "3-4 Years",
    category: "upgrading",
    code: "BSC-VCA-UPG",
    is_active: true,
    programme_type: "upgrading",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "• Diploma in Agriculture, Agribusiness, Livestock, Marketing, Entrepreneurship, Financial Accounting, Supply Chain\n• MSCE with at least 4 credits including English, Mathematics, Biology, Chemistry, Physics/Physical Science"
  },

  // GENERIC PROGRAMMES - FACULTY OF HEALTH SCIENCES
  {
    name: "Bachelor of Science in Nursing and Midwifery",
    description: "Professional nursing and midwifery programme preparing students for healthcare careers.",
    department: "Faculty of Health Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BSNM",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Health Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English, Mathematics/Add. Mathematics, Chemistry, Physics/Physical Science, Biology. Must specify Nursing as first choice",
    quota: 20
  },

  // GENERIC PROGRAMMES - FACULTY OF HUMANITIES AND SOCIAL SCIENCES
  {
    name: "Bachelor of Arts (Politics and Governance)",
    description: "Study of political systems, governance structures, and policy-making processes.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BPOL",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits in English, Mathematics + any 2 of: Geography, History, Bible Knowledge, Social and Development Studies, Business Studies",
    quota: 3
  },
  {
    name: "Bachelor of Arts (International Relations & Diplomacy)",
    description: "Study of international affairs, diplomatic practices, and global governance.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BIRD",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits in English, Mathematics + any 2 of: Geography, History, Bible Knowledge, Art, Social and Development Studies, Business Studies",
    quota: 3
  },
  {
    name: "Bachelor of Arts (Development Studies)",
    description: "Study of development theories, practices, and socio-economic transformation.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BDEV",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits in English, Mathematics + any 2 of: Business Studies, Geography, History, Social and Development Studies, Computer Studies",
    quota: 3
  },
  {
    name: "Bachelor of Arts (History and Heritage Studies)",
    description: "Study of historical events, cultural heritage, and preservation practices.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BHHS",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English, History + any 2 of: Geography, Bible Knowledge, Social Studies, Life Skills",
    quota: 5
  },
  {
    name: "Bachelor of Arts (Theology & Religious Studies)",
    description: "Study of religious traditions, theological concepts, and faith practices.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BTRS",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits in English + Bible Knowledge or History + any 1 of: Social and Development Studies, Geography, French",
    quota: 5
  },
  {
    name: "Bachelor of Arts (Communication Studies)",
    description: "Study of communication theories, media practices, and public relations.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BACOS",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English + any 2 of: Bible Knowledge, Chichewa, French, Geography, History, Social and Development Studies, Life Skills + at least a pass in Mathematics",
    quota: 4
  },
  {
    name: "Bachelor of Library and Information Science",
    description: "Study of library management, information systems, and knowledge organization.",
    department: "Faculty of Humanities and Social Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BLIS",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Humanities and Social Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English + any 2 of: History, Geography, Chichewa, French, Development Studies, Computer Studies, Bible Knowledge, Life Skills",
    quota: 5
  },

  // GENERIC PROGRAMMES - FACULTY OF SCIENCE, TECHNOLOGY AND INNOVATION
  {
    name: "Bachelor of Science (Honours) in Renewable Energy Systems Engineering",
    description: "Professional engineering programme focusing on renewable energy technologies and systems.",
    department: "Faculty of Science, Technology and Innovation",
    duration: "5 Years",
    category: "generic",
    code: "BRESE",
    is_active: true,
    programme_type: "generic", // CHANGED from "non-generic" to "generic"
    study_mode: "full time",
    school: "Faculty of Science, Technology and Innovation",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits in English, Mathematics/Add. Mathematics, Physics, Chemistry + 2 other subjects",
    quota: 10
  },
  {
    name: "Bachelor of Science in Information & Communication Technology",
    description: "Study of ICT systems, software development, and network technologies.",
    department: "Faculty of Science, Technology and Innovation",
    duration: "4 Years",
    category: "generic",
    code: "ICT",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Science, Technology and Innovation",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English, Mathematics + any 2 of: Physical Science/Physics & Chemistry, Biology, Computer Studies, Add. Mathematics, Agriculture, Home Economics, Geography",
    quota: 8
  },

  // GENERIC PROGRAMMES - FACULTY OF ENVIRONMENTAL SCIENCES
  {
    name: "Bachelor of Science (Forestry)",
    description: "Study of forest management, conservation, and sustainable resource utilization.",
    department: "Faculty of Environmental Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BScF",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English, Biology, Mathematics + any 3 science-related subjects (Physical Science/Physics & Chemistry, Agriculture, Geography, Computer Studies, Social and Development Studies, Business Studies, Home Economics)",
    quota: 30
  },
  {
    name: "Bachelor of Science (Fisheries & Aquatic Sciences)",
    description: "Study of aquatic ecosystems, fisheries management, and marine biology.",
    department: "Faculty of Environmental Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BSFS",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits in Biology, Physical Science/General Science, Mathematics/Add. Mathematics, English + any 2 credits from: Geography, Agriculture, Chemistry, Social and Development Studies, Home Economics, Business Studies",
    quota: 10
  },
  {
    name: "Bachelor of Science in Land Surveying",
    description: "Study of land measurement, mapping, and geospatial technologies.",
    department: "Faculty of Environmental Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BSLS",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including Mathematics, Geography, English, Physical Science/Physics & Chemistry, Agriculture, Social and Development Studies",
    quota: 10
  },
  {
    name: "Bachelor of Science in Estate Management",
    description: "Study of property management, real estate valuation, and land economics.",
    department: "Faculty of Environmental Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BSEM",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including Agriculture, English, Geography, Mathematics, Social and Development Studies",
    quota: 10
  },
  {
    name: "Bachelor of Science in Town & Regional Planning",
    description: "Study of urban planning, regional development, and spatial design.",
    department: "Faculty of Environmental Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BSTRP",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits in Mathematics, Geography, Agriculture, Social and Development Studies, English + any other subject",
    quota: 10
  },
  {
    name: "Bachelor of Science (Water Resources Engineering & Management)",
    description: "Study of water resource management, hydrology, and water systems engineering.",
    department: "Faculty of Environmental Sciences",
    duration: "4 Years",
    category: "generic",
    code: "BSWREM",
    is_active: true,
    programme_type: "generic", // CHANGED from "non-generic" to "generic"
    study_mode: "full time",
    school: "Faculty of Environmental Sciences",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including Mathematics/Add. Mathematics, Physical Science/Physics & Chemistry, English",
    quota: 20
  },

  // GENERIC PROGRAMMES - FACULTY OF TOURISM, HOSPITALITY AND MANAGEMENT
  {
    name: "Bachelor of Business (Tourism Management)",
    description: "Study of tourism business operations, destination management, and hospitality services.",
    department: "Faculty of Tourism, Hospitality and Management",
    duration: "4 Years",
    category: "generic",
    code: "BBTM",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Tourism, Hospitality and Management",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English and Mathematics",
    quota: 15
  },
  {
    name: "Bachelor of Arts (Culture and Heritage Tourism)",
    description: "Study of cultural heritage, tourism management, and preservation of traditions.",
    department: "Faculty of Tourism, Hospitality and Management",
    duration: "4 Years",
    category: "generic",
    code: "BACHT",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Tourism, Hospitality and Management",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English",
    quota: 15
  },
  {
    name: "Bachelor of Science (Hospitality Management)",
    description: "Study of hotel operations, event management, and hospitality business.",
    department: "Faculty of Tourism, Hospitality and Management",
    duration: "4 Years",
    category: "generic",
    code: "BSHM",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Tourism, Hospitality and Management",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English and Mathematics",
    quota: 15
  },
  {
    name: "Bachelor of Culinary Arts",
    description: "Study of culinary techniques, food preparation, and kitchen management.",
    department: "Faculty of Tourism, Hospitality and Management",
    duration: "4 Years",
    category: "generic",
    code: "BCUL",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Tourism, Hospitality and Management",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English and Mathematics",
    quota: 15
  },
  {
    name: "Bachelor of Arts (Sports Management)",
    description: "Study of sports administration, facility management, and athletic program development.",
    department: "Faculty of Tourism, Hospitality and Management",
    duration: "4 Years",
    category: "generic",
    code: "BASM",
    is_active: true,
    programme_type: "generic",
    study_mode: "full time",
    school: "Faculty of Tourism, Hospitality and Management",
    entry_requirements: "MSCE aggregate ≤30 points with at least 6 credits including English and Mathematics",
    quota: 15
  }
];